DROP INDEX "acm_contest_rank_contest_id_21030ccd";--> statement-breakpoint
DROP INDEX "acm_contest_rank_user_id_40391ab2";--> statement-breakpoint
DROP INDEX "flowchart_submission_id_0dbfc4f9_like";--> statement-breakpoint
DROP INDEX "flowchart_submission_problem_id_8551edbf";--> statement-breakpoint
DROP INDEX "flowchart_submission_user_id_225c83e8";--> statement-breakpoint
DROP INDEX "message_recipient_id_2aa5dd76";--> statement-breakpoint
DROP INDEX "message_submission_id_2fdf8a47_like";--> statement-breakpoint
DROP INDEX "problem__id_919b1d80";--> statement-breakpoint
DROP INDEX "problem_contest_id_328e013a";--> statement-breakpoint
DROP INDEX "problem_tags_problem_id_866ecb8d";--> statement-breakpoint
DROP INDEX "problemset_problem_problemset_id_350d17fb";--> statement-breakpoint
DROP INDEX "problemset_progress_problemset_id_20a9632e";--> statement-breakpoint
DROP INDEX "problemset_submission_problemset_id_85290e17";--> statement-breakpoint
DROP INDEX "problemset_submission_submission_id_78e2b807_like";--> statement-breakpoint
DROP INDEX "problemset_submission_user_id_915fc9c6";--> statement-breakpoint
DROP INDEX "reaction_problem_id_a7f3b9f3";--> statement-breakpoint
DROP INDEX "submission_contest_id_775716d5";--> statement-breakpoint
DROP INDEX "submission_problem_id_76847b55";--> statement-breakpoint
DROP INDEX "submission_user_id_3779a8c1";--> statement-breakpoint
DROP INDEX "user_achievement_user_id_b8ec7d6a";--> statement-breakpoint
DROP INDEX "user_badge_user_id_a286d718";