-- AI 提示的留痕与学生评价（AI 时代 OJ 设计 2a：先记录、不改行为），字段含义见 schema.ts 的 aiHint。
-- 纯建表。上线之前的提示从未落库，这张表从空开始。
CREATE TABLE "ai_hint" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ai_hint_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submission_id" text NOT NULL,
	"model" text NOT NULL,
	"prompt_version" integer NOT NULL,
	"content" text NOT NULL,
	"error" text,
	"duration_ms" integer NOT NULL,
	"helpful" boolean,
	"feedback_time" timestamp with time zone,
	"create_time" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "ai_hint" ADD CONSTRAINT "ai_hint_submission_id_fk_submission_id" FOREIGN KEY ("submission_id") REFERENCES "public"."submission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ai_hint_submission_id_idx" ON "ai_hint" USING btree ("submission_id");