CREATE TABLE "class_lesson" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "class_lesson_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"class_name" text NOT NULL,
	"day" text NOT NULL,
	"problem_ids" jsonb NOT NULL,
	"created_by" integer NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "class_lesson_class_day_unique" UNIQUE("class_name","day")
);
--> statement-breakpoint
ALTER TABLE "class_lesson" ADD CONSTRAINT "class_lesson_created_by_fk_user_id" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "class_lesson_created_by_idx" ON "class_lesson" USING btree ("created_by");